### PR TITLE
Make CopyTextArea margin configurable

### PR DESCRIPTION
**Pull request by flynn1999**

### CODE REVIEW

**Review by ash3rz — APPROVED** [review]
LGTM :shipit: 
I was hoping this PR would be coming from your [fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#keep-your-fork-synced), but that's ok.  When you merge this, remember to delete your branch from this repo (or someone can do it for you).

**Review by sri2k1us — APPROVED** [review]
:shipit: Also, please go thru the `Readme` before merging this. There are instructions on how to publish a new version of this lib.

**Comment by flynn1999** [comment]
> :shipit: Also, please go thru the `Readme` before merging this. There are instructions on how to publish a new version of this lib.

I have pushed it to master and ran `npm run deploy-storybook` according to the readme. 👍

**Comment by sri2k1us** [comment]
> > :shipit: Also, please go thru the `Readme` before merging this. There are instructions on how to publish a new version of this lib.
> 
> I have pushed it to master and ran `npm run deploy-storybook` according to the readme. 👍

The last github actions has failed. Did you figure out why ? I think you may have missed a step in `Read Me` (hint: version)

**Comment by flynn1999** [comment]
> > > :shipit: Also, please go thru the `Readme` before merging this. There are instructions on how to publish a new version of this lib.
> > 
> > 
> > I have pushed it to master and ran `npm run deploy-storybook` according to the readme. 👍
> 
> The last github actions has failed. Did you figure out why ? I think you may have missed a step in `Read Me` (hint: version)

So, I did read that I was supposed to update the version and originally I thought that meant updating the components through `npm run deploy-storybook`. Should I change the version line in `package.json` to `6.0.1` or some other number?

**Comment by sri2k1us** [comment]
> > > > :shipit: Also, please go thru the `Readme` before merging this. There are instructions on how to publish a new version of this lib.
> > > 
> > > 
> > > I have pushed it to master and ran `npm run deploy-storybook` according to the readme. 👍
> > 
> > 
> > The last github actions has failed. Did you figure out why ? I think you may have missed a step in `Read Me` (hint: version)
> 
> So, I did read that I was supposed to update the version and originally I thought that meant updating the components through `npm run deploy-storybook`. Should I change the version line in `package.json` to `6.0.1` or some other number?

No. Don't do it manually.  Use `npm version patch` and push your change.

**Pull request merged**
