### PR TITLE
Use lighter date-formatting code

### PR DESCRIPTION
**Pull request by ianmcorvidae**
Continuing with miscellaneous improvements as I dig into this stuff.

This removes the calls to `legacyParse` (updating to `toDate` -- the main difference is that `legacyParse` can take a string, but we're not passing it one, so it seems unnecessary), and switches to using `lightFormat` rather than `format`, which is the same but supports fewer of the weirder formatting things. I'm assuming we won't need things like quarters, day of year, etc, and this means we're importing a lot less of `date-fns`.

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
side note, with #40 in the picture this date formatting stuff doesn't even make it into sonora since we don't use any of the date-related stuff from ui-lib. But this is still a good idea, probably :)

**Comment by sri2k1us** [comment]
> side note, with #40 in the picture this date formatting stuff doesn't even make it into sonora since we don't use any of the date-related stuff from ui-lib. But this is still a good idea, probably :)

Thats weird, I know its been used in lot of places  in Sonora- 

Here is one:

https://github.com/cyverse-de/sonora/blob/385cfca91a6b79729e53cf5720b640f274dbd152/src/components/analyses/listing/TableView.js#L351

Not sure if we are talking about the same thing though 😕

**Comment by ianmcorvidae** [comment]
I think I'm mistaken and it _is_ in sonora, looking at it again. I think webpack can just optimize it down enough that it doesn't directly appear in the bundle analyzer view. (Which, I suppose, shows that this helped a lot!)

**Review by psarando — APPROVED** [review]
LGTM 👍

**Review by ash3rz — APPROVED** [review]
LGTM :shipit:

**Comment by ianmcorvidae** [comment]
Thanks for the reviews!

**Pull request merged**
